export const LOG_IN = 'LOG_IN';

export const SIGN_UP = 'SIGN_UP';
export const SUCCESS_SIGNUP_MESSAGE = 'SUCCESS_SIGNUP_MESSAGE';
export const ERROR_SIGNUP_MESSAGE = 'ERROR_SIGNUP_MESSAGE';

export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const ERROR_CREATE_ARTICLE = 'ERROR_CREATE_ARTICLE';

export const VIEW_ARTICLE = 'VIEW_ARTICLE';
export const VIEW_ARTICLE_ERROR = 'VIEW_ARTICLE_ERROR';
