export const LOG_IN = 'LOG_IN';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const SIGN_UP = 'SIGN_UP';

export const SUCCESS_SIGNUP_MESSAGE = 'SUCCESS_SIGNUP_MESSAGE';
export const ERROR_SIGNUP_MESSAGE = 'ERROR_SIGNUP_MESSAGE';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const ERROR_CREATE_ARTICLE = 'ERROR_CREATE_ARTICLE';
export const VIEW_ARTICLE = 'VIEW_ARTICLE';
export const VIEW_ARTICLE_ERROR = 'VIEW_ARTICLE_ERROR';
export const COMMENT_ON_ARTICLE = 'COMMENT_ON_ARTICLE';
export const GET_ARTICLE_COMMENTS = 'GET_ARTICLE_COMMENTS';
export const EDIT_COMMENT = 'EDIT_COMMENT';

export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES';
export const GET_ALL_ARTICLES_SUCCESS_MSG = 'GET_ALL_ARTICLES_SUCCESS_MSG';
export const GET_ALL_ARTICLES_FAILURE_MSG = 'GET_ALL_ARTICLES_FAILURE_MSG';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';
export const GET_USER_ARTICLES = 'GET_USER_ARTICLES';
export const GET_USER_ARTICLES_FAIL = 'GET_USER_ARTICLES_FAIL';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL';

export const GET_OTHER_PROFILE = 'GET_OTHER_PROFILE';
export const GET_OTHER_PROFILE_FAIL_MSG = 'GET_OTHER_PROFILE_FAIL_MSG';
export const LIKE = 'LIKE';
export const UNLIKE = 'UNLIKE';
export const LIKE_ERROR = 'LIKE_ERROR';
export const GET_ARTICLE = 'GET_ARTICLE';
export const SOCIAL_AUTH = 'SOCIAL_AUTH';

export const ARTICLE_RATING_ERROR = 'ARTICLE_RATING_ERROR';

export const SEARCH = 'SEARCH';

export const PASSWORD_RESET = 'PASSWORD_RESET';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

export const BOOKMARK = 'BOOKMARK';
export const BOOKMARK_ERROR = 'BOOKMARK_ERROR';
export const BOOKMARK_ON_ALL = 'BOOKMARK_ON_ALL';

export const UNBOOKMARK = 'UNBOOKMARK';
export const UNBOOKMARK_ERROR = 'UNBOOKMARK_ERROR';
export const UNBOOKMARK_ON_ALL = 'UNBOOKMARK_ON_ALL';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const FOLLOW = 'FOLLOW';
export const FOLLOW_FAIL_MSG = 'FOLLOW_FAIL_MSG';
export const UNFOLLOW = 'UNFOLLOW';
export const UNFOLLOW_FAIL_MSG = 'UNFOLLOW_FAIL_MSG';
export const FOLLOWERS = 'FOLLOWERS';
export const FOLLOWERS_FAIL_MSG = 'FOLLOWERS_FAIL_MSG';
export const FOLLOWING = 'FOLLOWING';
export const FOLLOWING_FAIL_MSG = 'FOLLOWING_FAIL_MSG';
export const GET_OTHER_FOLLOWERS = 'GET_OTHER_FOLLOWERS';
export const GET_OTHER_FOLLOWERS_FAIL_MSG = 'GET_OTHER_FOLLOWERS_FAIL_MSG';
