export const LOG_IN = 'LOG_IN';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const SIGN_UP = 'SIGN_UP';

export const SUCCESS_SIGNUP_MESSAGE = 'SUCCESS_SIGNUP_MESSAGE';
export const ERROR_SIGNUP_MESSAGE = 'ERROR_SIGNUP_MESSAGE';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const ERROR_CREATE_ARTICLE = 'ERROR_CREATE_ARTICLE';
export const VIEW_ARTICLE = 'VIEW_ARTICLE';
export const VIEW_ARTICLE_ERROR = 'VIEW_ARTICLE_ERROR';
export const COMMENT_ON_ARTICLE = 'COMMENT_ON_ARTICLE';
export const GET_ARTICLE_COMMENTS = 'GET_ARTICLE_COMMENTS';

export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES';
export const GET_ALL_ARTICLES_SUCCESS_MSG = 'GET_ALL_ARTICLES_SUCCESS_MSG';
export const GET_ALL_ARTICLES_FAILURE_MSG = 'GET_ALL_ARTICLES_FAILURE_MSG';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';

export const LIKE = 'LIKE';
export const UNLIKE = 'UNLIKE';
export const LIKE_ERROR = 'LIKE_ERROR';
export const GET_ARTICLE = 'GET_ARTICLE';
export const SOCIAL_AUTH = 'SOCIAL_AUTH';
export const ARTICLE_RATING_ERROR = 'ARTICLE_RATING_ERROR';
